function rawOut = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BAYERW000009 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  BAYERW000009 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  BayerW000009 = importfile("C:\Users\LBecce\Desktop\WPpostpro\WP5000-Post-Processing\Bayer_W 000009.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-May-2024 10:42:30

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "ma", "px", "py", "vx", "vy", "vz"];
opts.SelectedVariableNames = ["ma", "px", "py", "vx", "vy", "vz"];
opts.VariableTypes = ["string", "categorical", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "ma"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["px", "py", "vx", "vy", "vz"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["px", "py", "vx", "vy", "vz"], "ThousandsSeparator", ".");

% Import the data
rawOut = readtable(filename, opts);

end